nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173','https://universe.localhost','https://api.universe.localhost']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    allow_headers: ['Content-Type','Authorization']
    max_age: 3600
  paths:
    '^/': ~
